language: swift

osx_image: xcode12.3
env:
  matrix:
    - TEST_SDK=iphonesimulator11.0 OS=11.0 NAME='iPhone XR'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project MRefresh.xcodeproj -scheme MRefresh -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
view raw
